name: Deploy Railway
on:
  push:
    branches: [ main ]
    paths:
      - 'bot/**'
      - '.github/workflows/deploy-railway.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: railwayapp/action@v1
        with:
          service: ${{ secrets.RAILWAY_SERVICE_ID }}
          token: ${{ secrets.RAILWAY_TOKEN }}
          path: bot
